// Traducciones completas para todos los idiomas
const translations = {
    en: {
        "Inicio": "Home",
        "Servicios": "Services",
        "Nosotros": "About Us",
        "Portafolio": "Portfolio",
        "Contacto": "Contact",
        "Tema": "Theme",
        "Idioma": "Language",
        "Innovación que impulsa tu negocio": "Innovation that drives your business",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "Comprehensive solutions in energy, real estate, artistic representation and ecommerce to take your business to the next level.",
        "Nuestros Servicios": "Our Services",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "We offer specialized solutions in various sectors to meet your business needs.",
        "Soluciones Energéticas": "Energy Solutions",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "We implement renewable energy and energy efficiency projects to reduce costs and improve sustainability.",
        "Servicios Inmobiliarios": "Real Estate Services",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "Development, management and specialized advice in high-value residential and commercial projects.",
        "Representación Artística": "Artistic Representation",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "Comprehensive management of artistic careers in music, film, theater and visual arts.",
        "Soluciones Ecommerce": "Ecommerce Solutions",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "Custom platforms and digital marketing strategies to maximize your online sales.",
        "Más información": "More info",
        "Quiénes Somos": "About Us",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresa is a multidisciplinary group founded in 2010 with the mission of offering innovative solutions in various business sectors. Our team combines technical expertise with creativity to deliver exceptional results.",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente es único para nosotros, y nos enorgullece ser parte de su éxito.": "We believe in building long-term relationships based on transparency, excellence and added value. Each client is unique to us, and we are proud to be part of our clients' success.",
        "Años de experiencia": "Years of experience",
        "Clientes satisfechos": "Satisfied clients",
        "Proyectos completados": "Completed projects",
        "Premios reconocidos": "Recognized awards",
        "Nuestro Portafolio": "Our Portfolio",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "Some of our outstanding projects in different areas of specialization.",
        "Todos": "All",
        "Energía": "Energy",
        "Inmobiliaria": "Real Estate",
        "Arte": "Art",
        "Ecommerce": "Ecommerce",
        "Parque Solar Valle Verde": "Valle Verde Solar Park",
        "Instalación de 50MW para suministro energético sostenible": "50MW installation for sustainable energy supply",
        "Residencial Los Alamos": "Los Alamos Residential",
        "Complejo residencial de lujo con 120 unidades": "Luxury residential complex with 120 units",
        "Gira Musical 'Horizontes'": "'Horizons' Music Tour",
        "Producción y gestión de gira para artista emergente": "Production and management of tour for emerging artist",
        "Tienda Online Moda Urbana": "Urban Fashion Online Store",
        "Plataforma ecommerce con aumento de ventas del 300%": "Ecommerce platform with 300% sales increase",
        "Optimización Energética Industrial": "Industrial Energy Optimization",
        "Reducción de 35% en consumo para fábrica automotriz": "35% consumption reduction for automotive factory",
        "Torre Corporativa Financiera": "Financial Corporate Tower",
        "Diseño y desarrollo de espacio para 500 empleados": "Design and development of space for 500 employees",
        "Contáctanos": "Contact Us",
        "Nombre": "Name",
        "Email": "Email",
        "Servicio de interés": "Service of interest",
        "Seleccione un servicio": "Select a service",
        "Mensaje": "Message",
        "Enviar Mensaje": "Send Message",
        "Lunes a Viernes: 9:00 - 18:00": "Monday to Friday: 9:00 - 18:00",
        "Política de Privacidad": "Privacy Policy",
        "Términos y Condiciones": "Terms and Conditions",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "Designed and developed by E POINT REPRESENTACION GLOBAL",
        "Todos los derechos reservados.": "All rights reserved.",
        "¿Cambiar idioma a este idioma?": "Change language to this language?"
    },
    es: {}, 
    fr: {
        "Inicio": "Accueil",
        "Servicios": "Services",
        "Nosotros": "À propos",
        "Portafolio": "Portfolio",
        "Contacto": "Contact",
        "Tema": "Thème",
        "Idioma": "Langue",
        "Innovación que impulsa tu negocio": "L'innovation qui propulse votre entreprise",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "Solutions intégrales en énergie, immobilier, représentation artistique et ecommerce pour propulser votre entreprise au niveau supérieur.",
        "Nuestros Servicios": "Nos Services",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "Nous offrons des solutions spécialisées dans divers secteurs pour répondre aux besoins de votre entreprise.",
        "Soluciones Energéticas": "Solutions Énergétiques",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "Nous mettons en œuvre des projets d'énergie renouvelable et d'efficacité énergétique pour réduire les coûts et améliorer la durabilité.",
        "Servicios Inmobiliarios": "Services Immobiliers",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "Développement, gestion et conseil spécialisé dans des projets résidentiels et commerciaux de haute valeur.",
        "Representación Artística": "Représentation Artistique",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "Gestion intégrale de carrières artistiques en musique, cinéma, théâtre et arts visuels.",
        "Soluciones Ecommerce": "Solutions Ecommerce",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "Plateformes personnalisées et stratégies de marketing digital pour maximiser vos ventes en ligne.",
        "Más información": "Plus d'informations",
        "Quiénes Somos": "Qui Nous Sommes",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresa est un groupe multidisciplinaire fondé en 2010 avec pour mission d'offrir des solutions innovantes dans divers secteurs d'activité. Notre équipe combine expertise technique et créativité pour offrir des résultats exceptionnels.",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente es único para nosotros, y nos enorgullece ser parte de su éxito.": "Nous croyons en la construction de relations à long terme basées sur la transparence, l'excellence et la valeur ajoutée. Chaque client est unique pour nous, et nous sommes fiers de faire partie de leur succès.",
        "Años de experiencia": "Années d'expérience",
        "Clientes satisfechos": "Clients satisfaits",
        "Proyectos completados": "Projets complétés",
        "Premios reconocidos": "Prix reconnus",
        "Nuestro Portafolio": "Notre Portfolio",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "Certains de nos projets remarquables dans différents domaines de spécialisation.",
        "Todos": "Tous",
        "Energía": "Énergie",
        "Inmobiliaria": "Immobilier",
        "Arte": "Art",
        "Ecommerce": "Ecommerce",
        "Parque Solar Valle Verde": "Parc Solaire Valle Verde",
        "Instalación de 50MW para suministro energético sostenible": "Installation de 50MW pour un approvisionnement énergétique durable",
        "Residencial Los Alamos": "Résidentiel Los Alamos",
        "Complejo residencial de lujo con 120 unidades": "Complexe résidentiel de luxe avec 120 unités",
        "Gira Musical 'Horizontes'": "Tournée Musicale 'Horizons'",
        "Producción y gestión de gira para artista emergente": "Production et gestion de tournée pour artiste émergent",
        "Tienda Online Moda Urbana": "Boutique en ligne Mode Urbaine",
        "Plataforma ecommerce con aumento de ventas del 300%": "Plateforme ecommerce avec une augmentation des ventes de 300%",
        "Optimización Energética Industrial": "Optimisation Énergétique Industrielle",
        "Reducción de 35% en consumo para fábrica automotriz": "Réduction de 35% de la consommation pour une usine automobile",
        "Torre Corporativa Financiera": "Tour Corporative Financière",
        "Diseño y desarrollo de espacio para 500 empleados": "Conception et développement d'espace pour 500 employés",
        "Contáctanos": "Contactez-nous",
        "Nombre": "Nom",
        "Email": "Email",
        "Servicio de interés": "Service d'intérêt",
        "Seleccione un servicio": "Sélectionnez un service",
        "Mensaje": "Message",
        "Enviar Mensaje": "Envoyer le Message",
        "Lunes a Viernes: 9:00 - 18:00": "Lundi à Vendredi: 9:00 - 18:00",
        "Política de Privacidad": "Politique de Confidentialité",
        "Términos y Condiciones": "Termes et Conditions",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "Conçu et développé par E POINT REPRESENTACION GLOBAL",
        "Todos los derechos reservados.": "Tous droits réservés.",
        "¿Cambiar idioma a este idioma?": "Changer la langue à cette langue?"
    },
    de: {
        "Inicio": "Startseite",
        "Servicios": "Dienstleistungen",
        "Nosotros": "Über uns",
        "Portafolio": "Portfolio",
        "Contacto": "Kontakt",
        "Tema": "Thema",
        "Idioma": "Sprache",
        "Innovación que impulsa tu negocio": "Innovation, die Ihr Unternehmen vorantreibt",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "Umfassende Lösungen in den Bereichen Energie, Immobilien, künstlerische Vertretung und E-Commerce, um Ihr Unternehmen auf die nächste Stufe zu heben.",
        "Nuestros Servicios": "Unsere Dienstleistungen",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "Wir bieten spezialisierte Lösungen in verschiedenen Branchen an, um die Bedürfnisse Ihres Unternehmens zu erfüllen.",
        "Soluciones Energéticas": "Energielösungen",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "Wir setzen Projekte für erneuerbare Energien und Energieeffizienz um, um Kosten zu senken und die Nachhaltigkeit zu verbessern.",
        "Servicios Inmobiliarios": "Immobiliendienstleistungen",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "Entwicklung, Verwaltung und spezialisierte Beratung für hochwertige Wohn- und Gewerbeprojekte.",
        "Representación Artística": "Künstlerische Vertretung",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "Umfassende Betreuung künstlerischer Karrieren in Musik, Film, Theater und bildender Kunst.",
        "Soluciones Ecommerce": "E-Commerce-Lösungen",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "Maßgeschneiderte Plattformen und digitale Marketingstrategien, um Ihre Online-Verkäufe zu maximieren.",
        "Más información": "Mehr Informationen",
        "Quiénes Somos": "Über uns",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresa ist eine multidisziplinäre Gruppe, die 2010 mit der Mission gegründet wurde, innovative Lösungen in verschiedenen Geschäftsbereichen anzubieten. Unser Team kombiniert technische Expertise mit Kreativität, um außergewöhnliche Ergebnisse zu liefern.",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente es único para nosotros, y nos enorgullece ser parte de su éxito.": "Wir glauben an den Aufbau langfristiger Beziehungen, die auf Transparenz, Exzellenz und Mehrwert basieren. Jeder Kunde ist für uns einzigartig und wir sind stolz darauf, Teil seines Erfolgs zu sein.",
        "Años de experiencia": "Jahre Erfahrung",
        "Clientes satisfechos": "Zufriedene Kunden",
        "Proyectos completados": "Abgeschlossene Projekte",
        "Premios reconocidos": "Anerkannte Auszeichnungen",
        "Nuestro Portafolio": "Unser Portfolio",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "Einige unserer herausragenden Projekte in verschiedenen Fachgebieten.",
        "Todos": "Alle",
        "Energía": "Energie",
        "Inmobiliaria": "Immobilien",
        "Arte": "Kunst",
        "Ecommerce": "Ecommerce",
        "Parque Solar Valle Verde": "Valle Verde Solarpark",
        "Instalación de 50MW para suministro energético sostenible": "50MW-Anlage für nachhaltige Energieversorgung",
        "Residencial Los Alamos": "Los Alamos Wohnanlage",
        "Complejo residencial de lujo con 120 unidades": "Luxus-Wohnkomplex mit 120 Einheiten",
        "Gira Musical 'Horizontes'": "'Horizonte' Musiktournee",
        "Producción y gestión de gira para artista emergente": "Produktion und Management einer Tournee für einen aufstrebenden Künstler",
        "Tienda Online Moda Urbana": "Urban Fashion Online-Shop",
        "Plataforma ecommerce con aumento de ventas del 300%": "E-Commerce-Plattform mit 300% Umsatzsteigerung",
        "Optimización Energética Industrial": "Industrielle Energieoptimierung",
        "Reducción de 35% en consumo para fábrica automotriz": "35% Verbrauchsreduktion für Automobilfabrik",
        "Torre Corporativa Financiera": "Finanz-Corporate-Tower",
        "Diseño y desarrollo de espacio para 500 empleados": "Design und Entwicklung eines Arbeitsraums für 500 Mitarbeiter",
        "Contáctanos": "Kontaktieren Sie uns",
        "Nombre": "Name",
        "Email": "E-Mail",
        "Servicio de interés": "Interessensdienst",
        "Seleccione un servicio": "Wählen Sie einen Dienst aus",
        "Mensaje": "Nachricht",
        "Enviar Mensaje": "Nachricht senden",
        "Lunes a Viernes: 9:00 - 18:00": "Montag bis Freitag: 9:00 - 18:00",
        "Política de Privacidad": "Datenschutzrichtlinie",
        "Términos y Condiciones": "Geschäftsbedingungen",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "Entworfen und entwickelt von E POINT REPRESENTACION GLOBAL",
        "Todos los derechos reservados.": "Alle Rechte vorbehalten.",
        "¿Cambiar idioma a este idioma?": "Sprache zu dieser Sprache ändern?"
    },
    it: {
        "Inicio": "Home",
        "Servicios": "Servizi",
        "Nosotros": "Chi siamo",
        "Portafolio": "Portfolio",
        "Contacto": "Contatto",
        "Tema": "Tema",
        "Idioma": "Lingua",
        "Innovación que impulsa tu negocio": "Innovazione che guida il tuo business",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "Soluzioni integrate in energia, immobiliare, rappresentanza artistica e ecommerce per portare la tua azienda al livello successivo.",
        "Nuestros Servicios": "I nostri servizi",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "Offriamo soluzioni specializzate in diversi settori per soddisfare le esigenze della tua azienda.",
        "Soluciones Energéticas": "Soluzioni energetiche",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "Implementiamo progetti di energia rinnovabile ed efficienza energetica per ridurre i costi e migliorare la sostenibilità.",
        "Servicios Inmobiliarios": "Servizi immobiliari",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "Sviluppo, gestione e consulenza specializzata in progetti residenziali e commerciali di alto valore.",
        "Representación Artística": "Rappresentanza artistica",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "Gestione integrale di carriere artistiche in musica, cinema, teatro e arti visive.",
        "Soluciones Ecommerce": "Soluzioni Ecommerce",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "Piattaforme personalizzate e strategie di marketing digitale per massimizzare le vendite online.",
        "Más información": "Più informazioni",
        "Quiénes Somos": "Chi siamo",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresa è un gruppo multidisciplinare fondato nel 2010 con la missione di offrire soluzioni innovative in diversi settori aziendali. Il nostro team combina esperienza tecnica con creatività per offrire risultati eccezionali.",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente es único para nosotros, y nos enorgullece ser parte de su éxito.": "Crediamo nella costruzione di relazioni a lungo termine basate su trasparenza, eccellenza e valore aggiunto. Ogni cliente è unico per noi e siamo orgogliosi di essere parte del loro successo.",
        "Años de experiencia": "Anni di esperienza",
        "Clientes satisfechos": "Clienti soddisfatti",
        "Proyectos completados": "Progetti completati",
        "Premios reconocidos": "Premi riconosciuti",
        "Nuestro Portafolio": "Il nostro portfolio",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "Alcuni dei nostri progetti più importanti in diverse aree di specializzazione.",
        "Todos": "Tutti",
        "Energía": "Energia",
        "Inmobiliaria": "Immobiliare",
        "Arte": "Arte",
        "Ecommerce": "Ecommerce",
        "Parque Solar Valle Verde": "Parco Solare Valle Verde",
        "Instalación de 50MW para suministro energético sostenible": "Impianto da 50MW per fornitura energetica sostenibile",
        "Residencial Los Alamos": "Residenziale Los Alamos",
        "Complejo residencial de lujo con 120 unidades": "Complesso residenziale di lusso con 120 unità",
        "Gira Musical 'Horizontes'": "Tour Musicale 'Orizzonti'",
        "Producción y gestión de gira para artista emergente": "Produzione e gestione del tour per artista emergente",
        "Tienda Online Moda Urbana": "Negozio online Moda Urbana",
        "Plataforma ecommerce con aumento de ventas del 300%": "Piattaforma ecommerce con aumento delle vendite del 300%",
        "Optimización Energética Industrial": "Ottimizzazione energetica industriale",
        "Reducción de 35% en consumo para fábrica automotriz": "Riduzione del 35% dei consumi per fabbrica automobilistica",
        "Torre Corporativa Financiera": "Torre Corporate Finanziaria",
        "Diseño y desarrollo de espacio para 500 empleados": "Progettazione e sviluppo di spazi per 500 dipendenti",
        "Contáctanos": "Contattaci",
        "Nombre": "Nome",
        "Email": "Email",
        "Servicio de interés": "Servizio di interesse",
        "Seleccione un servicio": "Seleziona un servizio",
        "Mensaje": "Messaggio",
        "Enviar Mensaje": "Invia Messaggio",
        "Lunes a Viernes: 9:00 - 18:00": "Lunedì al Venerdì: 9:00 - 18:00",
        "Política de Privacidad": "Politica sulla privacy",
        "Términos y Condiciones": "Termini e condizioni",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "Progettato e sviluppato da E POINT REPRESENTACION GLOBAL",
        "Todos los derechos reservados.": "Tutti i diritti riservati.",
        "¿Cambiar idioma a este idioma?": "Cambiare la lingua a questa lingua?"
    },
    pt: {
        "Inicio": "Início",
        "Servicios": "Serviços",
        "Nosotros": "Sobre nós",
        "Portafolio": "Portfólio",
        "Contacto": "Contato",
        "Tema": "Tema",
        "Idioma": "Idioma",
        "Innovación que impulsa tu negocio": "Inovação que impulsiona seu negócio",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "Soluções integrais em energia, imobiliário, representação artística e ecommerce para levar sua empresa para o próximo nível.",
        "Nuestros Servicios": "Nossos Serviços",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "Oferecemos soluções especializadas em diversos setores para atender às necessidades do seu negócio.",
        "Soluciones Energéticas": "Soluções Energéticas",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "Implementamos projetos de energia renovável e eficiência energética para reduzir custos e melhorar a sustentabilidade.",
        "Servicios Inmobiliarios": "Serviços Imobiliários",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "Desenvolvimento, gestão e assessoria especializada em projetos residenciais e comerciais de alto valor.",
        "Representación Artística": "Representação Artística",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "Gestão integral de carreiras artísticas em música, cinema, teatro e artes visuais.",
        "Soluciones Ecommerce": "Soluções Ecommerce",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "Plataformas personalizadas e estratégias de marketing digital para maximizar suas vendas online.",
        "Más información": "Mais informações",
        "Quiénes Somos": "Quem Somos",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresa é um grupo multidisciplinar fundado em 2010 com a missão de oferecer soluções inovadoras em diversos setores empresariais. Nossa equipe combina experiência técnica com criatividade para oferecer resultados excepcionais.",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente es único para nosotros, y nos enorgullece ser parte de su éxito.": "Acreditamos em construir relacionamentos de longo prazo baseados em transparência, excelência e valor agregado. Cada cliente é único para nós e temos orgulho de fazer parte do seu sucesso.",
        "Años de experiencia": "Anos de experiência",
        "Clientes satisfechos": "Clientes satisfeitos",
        "Proyectos completados": "Projetos completados",
        "Premios reconocidos": "Prêmios reconhecidos",
        "Nuestro Portafolio": "Nosso Portfólio",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "Alguns dos nossos projetos destacados em diferentes áreas de especialização.",
        "Todos": "Todos",
        "Energía": "Energia",
        "Inmobiliaria": "Imobiliário",
        "Arte": "Arte",
        "Ecommerce": "Ecommerce",
        "Parque Solar Valle Verde": "Parque Solar Valle Verde",
        "Instalación de 50MW para suministro energético sostenible": "Instalação de 50MW para fornecimento de energia sustentável",
        "Residencial Los Alamos": "Residencial Los Alamos",
        "Complejo residencial de lujo con 120 unidades": "Complexo residencial de luxo com 120 unidades",
        "Gira Musical 'Horizontes'": "Turnê Musical 'Horizontes'",
        "Producción y gestión de gira para artista emergente": "Produção e gestão de turnê para artista emergente",
        "Tienda Online Moda Urbana": "Loja Online Moda Urbana",
        "Plataforma ecommerce con aumento de ventas del 300%": "Plataforma ecommerce com aumento de vendas de 300%",
        "Optimización Energética Industrial": "Otimização Energética Industrial",
        "Reducción de 35% en consumo para fábrica automotriz": "Redução de 35% no consumo para fábrica automotiva",
        "Torre Corporativa Financiera": "Torre Corporativa Financeira",
        "Diseño y desarrollo de espacio para 500 empleados": "Design e desenvolvimento de espaço para 500 funcionários",
        "Contáctanos": "Contate-nos",
        "Nombre": "Nome",
        "Email": "Email",
        "Servicio de interés": "Serviço de interesse",
        "Seleccione un servicio": "Selecione um serviço",
        "Mensaje": "Mensagem",
        "Enviar Mensaje": "Enviar Mensagem",
        "Lunes a Viernes: 9:00 - 18:00": "Segunda a Sexta: 9:00 - 18:00",
        "Política de Privacidad": "Política de Privacidade",
        "Términos y Condiciones": "Termos e Condições",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "Projetado e desenvolvido por E POINT REPRESENTACION GLOBAL",
        "Todos los derechos reservados.": "Todos os direitos reservados.",
        "¿Cambiar idioma a este idioma?": "Mudar o idioma para este idioma?"
    },
    ru: {
        "Inicio": "Главная",
        "Servicios": "Услуги",
        "Nosotros": "О нас",
        "Portafolio": "Портфолио",
        "Contacto": "Контакты",
        "Tema": "Тема",
        "Idioma": "Язык",
        "Innovación que impulsa tu negocio": "Инновации, которые двигают ваш бизнес",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "Комплексные решения в области энергетики, недвижимости, художественного представительства и электронной коммерции для вывода вашего бизнеса на новый уровень.",
        "Nuestros Servicios": "Наши услуги",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "Мы предлагаем специализированные решения в различных секторах для удовлетворения потребностей вашего бизнеса.",
        "Soluciones Energéticas": "Энергетические решения",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "Мы реализуем проекты в области возобновляемой энергии и энергоэффективности для снижения затрат и повышения устойчивости.",
        "Servicios Inmobiliarios": "Услуги недвижимости",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "Разработка, управление и специализированное консультирование по жилым и коммерческим проектам высокой стоимости.",
        "Representación Artística": "Художественное представительство",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "Комплексное управление художественной карьерой в музыке, кино, театре и изобразительном искусстве.",
        "Soluciones Ecommerce": "Решения для электронной коммерции",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "Индивидуальные платформы и стратегии цифрового маркетинга для максимизации ваших онлайн-продаж.",
        "Más información": "Подробнее",
        "Quiénes Somos": "О нас",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresa - это многопрофильная группа, основанная в 2010 году с миссией предлагать инновационные решения в различных бизнес-секторах. Наша команда сочетает технический опыт с творчеством, чтобы обеспечить исключительные результаты.",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente es único para nosotros, y nos enorgullece ser parte de su éxito.": "Мы верим в построение долгосрочных отношений, основанных на прозрачности, превосходстве и добавленной стоимости. Каждый клиент уникален для нас, и мы гордимся тем, что являемся частью их успеха.",
        "Años de experiencia": "Лет опыта",
        "Clientes satisfechos": "Довольных клиентов",
        "Proyectos completados": "Завершенных проектов",
        "Premios reconocidos": "Признанных наград",
        "Nuestro Portafolio": "Наше портфолио",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "Некоторые из наших выдающихся проектов в различных областях специализации.",
        "Todos": "Все",
        "Energía": "Энергетика",
        "Inmobiliaria": "Недвижимость",
        "Arte": "Искусство",
        "Ecommerce": "Электронная коммерция",
        "Parque Solar Valle Verde": "Солнечный парк Валле Верде",
        "Instalación de 50MW para suministro energético sostenible": "Установка мощностью 50 МВт для устойчивого энергоснабжения",
        "Residencial Los Alamos": "Жилой комплекс Лос Аламос",
        "Complejo residencial de lujo con 120 unidades": "Роскошный жилой комплекс с 120 квартирами",
        "Gira Musical 'Horizontes'": "Музыкальный тур 'Горизонты'",
        "Producción y gestión de gira para artista emergente": "Производство и управление туром для начинающего артиста",
        "Tienda Online Moda Urbana": "Онлайн-магазин Urban Fashion",
        "Plataforma ecommerce con aumento de ventas del 300%": "Платформа электронной коммерции с увеличением продаж на 300%",
        "Optimización Energética Industrial": "Промышленная энергооптимизация",
        "Reducción de 35% en consumo para fábrica automotriz": "Снижение потребления на 35% для автомобильного завода",
        "Torre Corporativa Financiera": "Финансовая корпоративная башня",
        "Diseño y desarrollo de espacio para 500 empleados": "Дизайн и разработка пространства для 500 сотрудников",
        "Contáctanos": "Свяжитесь с нами",
        "Nombre": "Имя",
        "Email": "Электронная почта",
        "Servicio de interés": "Интересующая услуга",
        "Seleccione un servicio": "Выберите услугу",
        "Mensaje": "Сообщение",
        "Enviar Mensaje": "Отправить сообщение",
        "Lunes a Viernes: 9:00 - 18:00": "Понедельник-Пятница: 9:00 - 18:00",
        "Política de Privacidad": "Политика конфиденциальности",
        "Términos y Condiciones": "Условия и положения",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "Разработано E POINT REPRESENTACION GLOBAL",
        "Todos los derechos reservados.": "Все права защищены.",
        "¿Cambiar idioma a este idioma?": "Изменить язык на этот язык?"
    },
    zh: {
        "Inicio": "首页",
        "Servicios": "服务",
        "Nosotros": "关于我们",
        "Portafolio": "作品集",
        "Contacto": "联系我们",
        "Tema": "主题",
        "Idioma": "语言",
        "Innovación que impulsa tu negocio": "推动您业务发展的创新",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "能源、房地产、艺术代表和电子商务的综合解决方案，将您的业务提升到新的水平。",
        "Nuestros Servicios": "我们的服务",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "我们提供各行业的专业解决方案，满足您的业务需求。",
        "Soluciones Energéticas": "能源解决方案",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "我们实施可再生能源和能源效率项目，以降低成本并提高可持续性。",
        "Servicios Inmobiliarios": "房地产服务",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "高价值住宅和商业项目的开发、管理和专业咨询。",
        "Representación Artística": "艺术代表",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "音乐、电影、戏剧和视觉艺术领域的艺术生涯综合管理。",
        "Soluciones Ecommerce": "电子商务解决方案",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "定制平台和数字营销策略，最大化您的在线销售。",
        "Más información": "更多信息",
        "Quiénes Somos": "关于我们",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresa是一家成立于2010年的多学科集团，致力于在各个商业领域提供创新解决方案。我们的团队将技术专长与创造力相结合，提供卓越的成果。",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente es único para nosotros, y nos enorgullece ser parte de su éxito.": "我们相信建立基于透明度、卓越和附加价值的长期关系。每个客户对我们来说都是独一无二的，我们很自豪能成为他们成功的一部分。",
        "Años de experiencia": "年经验",
        "Clientes satisfechos": "满意客户",
        "Proyectos completados": "完成项目",
        "Premios reconocidos": "认可奖项",
        "Nuestro Portafolio": "我们的作品集",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "我们在不同专业领域的一些杰出项目。",
        "Todos": "全部",
        "Energía": "能源",
        "Inmobiliaria": "房地产",
        "Arte": "艺术",
        "Ecommerce": "电子商务",
        "Parque Solar Valle Verde": "绿谷太阳能公园",
        "Instalación de 50MW para suministro energético sostenible": "50兆瓦可持续能源供应设施",
        "Residencial Los Alamos": "洛斯阿拉莫斯住宅区",
        "Complejo residencial de lujo con 120 unidades": "120套豪华住宅综合体",
        "Gira Musical 'Horizontes'": "音乐巡演'地平线'",
        "Producción y gestión de gira para artista emergente": "为新兴艺术家制作和管理巡演",
        "Tienda Online Moda Urbana": "都市时尚在线商店",
        "Plataforma ecommerce con aumento de ventas del 300%": "销售额增长300%的电子商务平台",
        "Optimización Energética Industrial": "工业能源优化",
        "Reducción de 35% en consumo para fábrica automotriz": "汽车工厂能耗降低35%",
        "Torre Corporativa Financiera": "金融企业大厦",
        "Diseño y desarrollo de espacio para 500 empleados": "为500名员工设计和开发的空间",
        "Contáctanos": "联系我们",
        "Nombre": "姓名",
        "Email": "电子邮件",
        "Servicio de interés": "感兴趣的服务",
        "Seleccione un servicio": "选择服务",
        "Mensaje": "消息",
        "Enviar Mensaje": "发送消息",
        "Lunes a Viernes: 9:00 - 18:00": "周一至周五: 9:00 - 18:00",
        "Política de Privacidad": "隐私政策",
        "Términos y Condiciones": "条款和条件",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "由E POINT REPRESENTACION GLOBAL设计和开发",
        "Todos los derechos reservados.": "保留所有权利。",
        "¿Cambiar idioma a este idioma?": "更改为这种语言？"
    },
    ja: {
        "Inicio": "ホーム",
        "Servicios": "サービス",
        "Nosotros": "私たちについて",
        "Portafolio": "ポートフォリオ",
        "Contacto": "お問い合わせ",
        "Tema": "テーマ",
        "Idioma": "言語",
        "Innovación que impulsa tu negocio": "ビジネスを推進するイノベーション",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "エネルギー、不動産、芸術代理、eコマースの包括的なソリューションで、ビジネスを次のレベルへ導きます。",
        "Nuestros Servicios": "私たちのサービス",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "ビジネスのニーズを満たすために、さまざまな分野で専門的なソリューションを提供しています。",
        "Soluciones Energéticas": "エネルギーソリューション",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "コスト削減と持続可能性向上のため、再生可能エネルギーとエネルギー効率プロジェクトを実施します。",
        "Servicios Inmobiliarios": "不動産サービス",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "高価値の住宅および商業プロジェクトの開発、管理、専門的なアドバイス。",
        "Representación Artística": "芸術代理",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "音楽、映画、演劇、視覚芸術における芸術的キャリアの包括的な管理。",
        "Soluciones Ecommerce": "Eコマースソリューション",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "オンライン販売を最大化するためのカスタムプラットフォームとデジタルマーケティング戦略。",
        "Más información": "詳細情報",
        "Quiénes Somos": "私たちについて",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresaは2010年に設立された多分野グループで、さまざまなビジネスセクターに革新的なソリューションを提供することを使命としています。私たちのチームは技術的専門知識と創造性を組み合わせ、卓越した結果を提供します。",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente es único para nosotros, y nos enorgullece ser parte de su éxito.": "透明性、卓越性、付加価値に基づいた長期的な関係の構築を信じています。各クライアントは私たちにとってユニークであり、その成功の一員であることを誇りに思っています。",
        "Años de experiencia": "年の経験",
        "Clientes satisfechos": "満足したクライアント",
        "Proyectos completados": "完了したプロジェクト",
        "Premios reconocidos": "認められた賞",
        "Nuestro Portafolio": "私たちのポートフォリオ",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "さまざまな専門分野における私たちの注目プロジェクト。",
        "Todos": "すべて",
        "Energía": "エネルギー",
        "Inmobiliaria": "不動産",
        "Arte": "芸術",
        "Ecommerce": "Eコマース",
        "Parque Solar Valle Verde": "バジェベルデソーラーパーク",
        "Instalación de 50MW para suministro energético sostenible": "持続可能なエネルギー供給のための50MW施設",
        "Residencial Los Alamos": "ロスアラモス住宅地",
        "Complejo residencial de lujo con 120 unidades": "120ユニットの豪華住宅団地",
        "Gira Musical 'Horizontes'": "音楽ツアー「ホリゾンテス」",
        "Producción y gestión de gira para artista emergente": "新進アーティストのためのツアー制作と管理",
        "Tienda Online Moda Urbana": "オンラインストア アーバンファッション",
        "Plataforma ecommerce con aumento de ventas del 300%": "売上300％増のEコマースプラットフォーム",
        "Optimización Energética Industrial": "産業用エネルギー最適化",
        "Reducción de 35% en consumo para fábrica automotriz": "自動車工場の消費量35％削減",
        "Torre Corporativa Financiera": "金融コーポレートタワー",
        "Diseño y desarrollo de espacio para 500 empleados": "500名の従業員のためのスペース設計と開発",
        "Contáctanos": "お問い合わせ",
        "Nombre": "名前",
        "Email": "メール",
        "Servicio de interés": "興味のあるサービス",
        "Seleccione un servicio": "サービスを選択",
        "Mensaje": "メッセージ",
        "Enviar Mensaje": "メッセージを送る",
        "Lunes a Viernes: 9:00 - 18:00": "月曜日から金曜日: 9:00 - 18:00",
        "Política de Privacidad": "プライバシーポリシー",
        "Términos y Condiciones": "利用規約",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "E POINT REPRESENTACION GLOBALによって設計・開発",
        "Todos los derechos reservados.": "無断複写・転載を禁じます。",
        "¿Cambiar idioma a este idioma?": "この言語に変更しますか？"
    },
    ar: {
        "Inicio": "الصفحة الرئيسية",
        "Servicios": "الخدمات",
        "Nosotros": "من نحن",
        "Portafolio": "محفظة الأعمال",
        "Contacto": "اتصل بنا",
        "Tema": "السمة",
        "Idioma": "اللغة",
        "Innovación que impulsa tu negocio": "الابتكار الذي يدفع عملك",
        "Soluciones integrales en energía, inmobiliaria, representación artística y ecommerce para llevar tu empresa al siguiente nivel.": "حلول متكاملة في الطاقة والعقارات والتمثيل الفني والتجارة الإلكترونية لدفع شركتك إلى المستوى التالي.",
        "Nuestros Servicios": "خدماتنا",
        "Ofrecemos soluciones especializadas en diversos sectores para satisfacer las necesidades de tu negocio.": "نقدم حلولًا متخصصة في مختلف القطاعات لتلبية احتياجات عملك.",
        "Soluciones Energéticas": "حلول الطاقة",
        "Implementamos proyectos de energía renovable y eficiencia energética para reducir costos y mejorar sostenibilidad.": "ننفذ مشاريع الطاقة المتجددة وكفاءة الطاقة لتقليل التكاليف وتحسين الاستدامة.",
        "Servicios Inmobiliarios": "الخدمات العقارية",
        "Desarrollo, gestión y asesoría especializada en proyectos residenciales y comerciales de alto valor.": "تطوير وإدارة واستشارات متخصصة في المشاريع السكنية والتجارية عالية القيمة.",
        "Representación Artística": "التمثيل الفني",
        "Gestión integral de carreras artísticas en música, cine, teatro y artes visuales.": "إدارة متكاملة للمهن الفنية في الموسيقى والسينما والمسرح والفنون البصرية.",
        "Soluciones Ecommerce": "حلول التجارة الإلكترونية",
        "Plataformas personalizadas y estrategias de marketing digital para maximizar tus ventas online.": "منصات مخصصة واستراتيجيات التسويق الرقمي لتعظيم مبيعاتك عبر الإنترنت.",
        "Más información": "مزيد من المعلومات",
        "Quiénes Somos": "من نحن",
        "MiEmpresa es un grupo multidisciplinario fundado en 2010 con la misión de ofrecer soluciones innovadoras en diversos sectores empresariales. Nuestro equipo combina experiencia técnica con creatividad para ofrecer resultados excepcionales.": "MiEmpresa هي مجموعة متعددة التخصصات تأسست عام 2010 بمهمة تقديم حلول مبتكرة في مختلف القطاعات التجارية. يجمع فريقنا بين الخبرة الفنية والإبداع لتقديم نتائج استثنائية.",
        "Creemos en construir relaciones a largo plazo basadas en la transparencia, la excelencia y el valor agregado. Cada cliente هو فريد بالنسبة لنا، ونحن فخورون بأن نكون جزءًا من نجاحه.": "نحن نؤمن ببناء علاقات طويلة الأمد تقوم على الشفافية والتميز والقيمة المضافة. كل عميل فريد بالنسبة لنا، ونحن فخورون بأن نكون جزءًا من نجاحه.",
        "Años de experiencia": "سنوات الخبرة",
        "Clientes satisfechos": "عملاء راضون",
        "Proyectos completados": "مشاريع مكتملة",
        "Premios reconocidos": "جوائز معترف بها",
        "Nuestro Portafolio": "محفظة أعمالنا",
        "Algunos de nuestros proyectos destacados en diferentes áreas de especialización.": "بعض من مشاريعنا البارزة في مختلف مجالات التخصص.",
        "Todos": "الكل",
        "Energía": "الطاقة",
        "Inmobiliaria": "العقارات",
        "Arte": "الفن",
        "Ecommerce": "التجارة الإلكترونية",
        "Parque Solar Valle Verde": "حديقة فالي فيردي للطاقة الشمسية",
        "Instalación de 50MW para suministro energético sostenible": "تركيب 50 ميجاوات لتوفير إمدادات طاقة مستدامة",
        "Residencial Los Alamos": "مجمع لوس ألاموس السكني",
        "Complejo residencial de lujo con 120 unidades": "مجمع سكني فاخر يتكون من 120 وحدة",
        "Gira Musical 'Horizontes'": "جولة موسيقية 'آفاق'",
        "Producción y gestión de gira para artista emergente": "إنتاج وإدارة جولة لفنان ناشئ",
        "Tienda Online Moda Urbana": "متجر أونلاين للموضة الحضرية",
        "Plataforma ecommerce con aumento de ventas del 300%": "منصة تجارة إلكترونية مع زيادة في المبيعات بنسبة 300٪",
        "Optimización Energética Industrial": "تحسين الطاقة الصناعية",
        "Reducción de 35% en consumo para fábrica automotriz": "خفض استهلاك الطاقة بنسبة 35٪ لمصنع سيارات",
        "Torre Corporativa Financiera": "برج الشركات المالية",
        "Diseño y desarrollo de espacio para 500 empleados": "تصميم وتطوير مساحة لـ 500 موظف",
        "Contáctanos": "اتصل بنا",
        "Nombre": "الاسم",
        "Email": "البريد الإلكتروني",
        "Servicio de interés": "الخدمة المطلوبة",
        "Seleccione un servicio": "اختر خدمة",
        "Mensaje": "الرسالة",
        "Enviar Mensaje": "إرسال الرسالة",
        "Lunes a Viernes: 9:00 - 18:00": "من الاثنين إلى الجمعة: 9:00 - 18:00",
        "Política de Privacidad": "سياسة الخصوصية",
        "Términos y Condiciones": "الشروط والأحكام",
        "Diseñado y desarrollado por E POINT REPRESENTACION GLOBAL": "صمم وطور بواسطة E POINT REPRESENTACION GLOBAL",
        "Todos los derechos reservados.": "جميع الحقوق محفوظة.",
        "¿Cambiar idioma a este idioma?": "تغيير اللغة إلى هذه اللغة؟"
    }
};